dividend = int(input("Enter a dividend: "))
divisor = int(input("Enter a divisor: "))
quotient = int(dividend // divisor)
remainder = int(dividend % divisor)
print(f"The result of {dividend} / {divisor} is {quotient}, and the remainder is {remainder}")